### ISSUE TITLE
Hotkeys for duplicating sequences

### ISSUE THREAD

**Issue by Chordian** [Chordian/sidfactory2#20]
As originally planned.

Could be especially nice if it automatically replaces the old sequence completely. So `A005` becomes `A02F` in the same position without increasing or decreasing the orderlist, ready to make unique changes.

So, **Ctrl+D** is like **Ctrl+C**, **Delete**, **Ctrl+F** and **Ctrl+V**.

The target for the duplication should be the next empty and unused sequence, the same functionality as #47

**Comment by Chordian** [comment]
_This is a task migrated from workstreams in Slack._

**Comment by micheldebree** [comment]
> If you know both the source and the destrination sequence index, you just copy data directly.

Something like:

sequence_source_index and sequence_destination_index should be known.. dest would be the one you found as the first unused one and source the one you wanna duplicate// Get the data source containers of the two sequences
const auto& sequence_data_source = m_DataSourceSequenceList[sequence_source_index];
auto& sequence_data_destination = m_DataSourceSequenceList[sequence_destination_index];// Get the length of the source
const int source_length = sequence_data_source->GetLength();// Make the length of the destination sequence the same as the source
sequence_data_destination->SetLength(source_length);// Copy all events from source to destination
for (int i = 0; i < source_length; ++i)
	(*sequence_data_destination)[i] = (*sequence_data_source)[i];

23:57
Now you also need to insert the new sequence index into the orderlist at the current orderlist index.
23:58
And finally you need to signal the sequence and orderlist data change, so that the will be repacked.
23:58
And to make everything look correct in the editor, tell the component that it needs to be redrawn!


OnSequenceChange(index) will force repacking of the sequence (which in your case should be the destination)
00:00
Orderlist repack is similar: OnOrderListChanged()
00:01
and probably also call UpdateMaxEventPos
00:01
Looking at those methods, I can see that they both ask for the component to be redrawn, so you don't need to worry about that!
00:02
As for how all this is packaged with undo etc., just have a look at DoInsertFirstFreeSequence()
00:02
Then you should have all the info you need..
00:03
If you look for where this method is called from, you should also have a good hint as to how to hook up the key map for it..
00:03
Remember to add the default key mapping in the class where that is setup - which I can't remember!

**Comment by micheldebree** [comment]
I implemented this so it doesn't remove the current sequence that is duplicated. Because this is more in line with how other DAW's and video editing software etc. work, and how I would expect it to work here. They usually put a copy of the clip being duplicated next to the original. To me it would be confusing to only see the number of the sequence change and not knowing what happened to the original, or even what its number was.
It is also more in line with my own workflow; I would use it more often to extend a melody, bassline or drumtrack then to replace it with a different version.
